### ISSUE TITLE
AppleSupportDownloadInfoProvider.py needs update for Python 3

### ISSUE THREAD

**Issue by jazzace** [autopkg/n8felton-recipes#110]
While testing AutoPkg 2.0RC1, I found that AppleSupportDownloadInfoProvider.py breaks under Python 3 due to syntax. The recipe of mine that broke said:
```
 line 78
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
```

**Comment by macmule** [comment]
Already addressed, but also addressed in #119
