### ISSUE TITLE
AmazonCorretto recipe failing to find download link

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/n8felton-recipes#111]
The AmazonCorretto recipe is failing for both versions 8 and 11, with an error like:

Error in local.munki.AmazonCorretto11: Processor: URLTextSearcher: Error: No match found on URL: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

Full text of a verbose run is attached.
[out.txt](https://github.com/autopkg/n8felton-recipes/files/3978440/out.txt)

If I run curl against the URL above it looks like all the download links are being inserted via JavaScript so I'm assuming this is the error. Not sure if it's possible to work around that?

**Comment by n8felton** [comment]
Leaving notes for myself to finish this later.

Found this: https://github.com/awsdocs/amazon-corretto-11-user-guide/blob/7f4904052677d104e2d3ed7c4d3a572b2c31d0fc/doc_source/downloads-list.md#using-permanent-urls
Need to switch to https://corretto.aws/downloads/latest/amazon-corretto-11-x64-macos-jdk.pkg (and the v8 version as well)

**Comment by n8felton** [comment]
Might also be good to implement the checksum stuff too, seeing how it's available.

**Comment by n8felton** [comment]
Partially pending https://github.com/corretto/corretto-11/pull/68
