### ISSUE TITLE
NaturalReaderFree recipes not downloading current version

### ISSUE THREAD

**Issue by vmiller** [autopkg/n8felton-recipes#114]
I noticed the NaturalReaderFree recipes are downloading version 14, and the current version of the software is 16.

**Comment by cwhits** [comment]
Fun. The link is no longer populated on their site with an actual download. Instead some javascript sets the href. 

Best case scenario: @n8felton will find some feed it uses for checking for updates after he installs it on his machine.

Worse case scenario: we curl https://www.naturalreaders.com/comfiles/software/js/software.js and look for a pkg on a line that's not commented out.

**Comment by vmiller** [comment]
Looks like it is an Electron app using the Squirrel framework for updates.

**Comment by cwhits** [comment]
can you find a URL for where it's getting the updates from?

**Comment by vmiller** [comment]
I haven't been able to yet :-)   I'll poke at it as time permits.

**Comment by vmiller** [comment]
I threw Charles Proxy on a test machine with NaturalReader installed.  The update check is hitting http://5iusryxinl.execute-api.us-east-1.amazonaws.com  and is passing binary data.  Probably a dead end unless I'm missing something.

**Comment by cwhits** [comment]
> The update check is hitting http://5iusryxinl.execute-api.us-east-1.amazonaws.com and is passing binary data.

we've gotten nowhere with this, but that URL doesn't exist any more. I still think (unfortunately) that the current best scenario is scraping software.js for a pkg that's not commented out.
