### ISSUE TITLE
AppleSupportDownloadInfoProvider.py url error

### ISSUE THREAD

**Issue by eshirk** [autopkg/n8felton-recipes#118]
Began seeing the following after yesterday's commit:

Processor: com.github.n8felton.shared/AppleSupportDownloadInfoProvider: Error: 'url'

**Comment by dcoobs** [comment]
},
 'verbose': 4}
com.github.n8felton.shared/AppleSupportDownloadInfoProvider
{'Input': {'ARTICLE_NUMBER': u'1927'}}
AppleSupportDownloadInfoProvider: Article URL: https://support.apple.com/kb/DL1927
AppleSupportDownloadInfoProvider: Download URL: https://support.apple.com/downloads/DL1927/en_US/&
'url'
Failed.
```

**Comment by jazzace** [comment]
It appears that Apple changed the URL format for specifying locale. For example, if I try to load https://support.apple.com/kb/DL2020 in a browser, it will redirect to https://support.apple.com/kb/DL2020?locale=en_CA (where en_CA is the locale – Canada, in my case). The processor assumes the format is https://support.apple.com/kb/DL2020/en_US/….

**Comment by dcoobs** [comment]
I believe the locale change only affects the article URL as the download URL still seems to be redirecting and downloading the dmg just fine for me in a web browser.

After updating to Autopkg v2, I'm getting some more helpful errors:
```
 'verbose': 4}
com.github.n8felton.shared/AppleSupportDownloadInfoProvider
{'Input': {'ARTICLE_NUMBER': '1888'}}
AppleSupportDownloadInfoProvider: Article URL: https://support.apple.com/kb/DL1888
AppleSupportDownloadInfoProvider: Download URL: https://support.apple.com/downloads/DL1888/en_US/&
AppleSupportDownloadInfoProvider: Curl command: ['/usr/bin/curl', '--compressed', '--location', '--head', 'https://support.apple.com/downloads/DL1888/en_US/&']
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 480, in process
    self.main()
  File "/Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes/SharedProcessors/AppleSupportDownloadInfoProvider.py", line 115, in main
    full_url = self.get_headers(download_url).get("http_redirected")
  File "/Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes/SharedProcessors/AppleSupportDownloadInfoProvider.py", line 65, in get_headers
    headers = self.parse_headers(curl_output)
  File "/Library/AutoPkg/autopkglib/URLGetter.py", line 163, in parse_headers
    elif self.env["url"].startswith("ftp://"):
KeyError: 'url'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 673, in process
    self.env = processor.process()
'url'
Failed.
```

**Comment by porkcube** [comment]
Ended up reverting to before this was merged until it's fixed:
```
cd ~/Library/Autopkg/RecipeRepos/com.github.autopkg.n8felton-recipes
git checkout fcf39bbc73723909046304d87c5b203115284afa
```
be sure to also run `autopkg update-trust-info` for any recipes used that depend on this processor.
