### ISSUE TITLE
%ASSET_REGEX% differentiate between architecture-based packages?

### ISSUE THREAD

**Issue by klou** [autopkg/n8felton-recipes#132]
Example:  KeePassXC

```
<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>KeePassXC</string>
		<key>ASSET_REGEX</key>
		<string>KeePassXC-.*(?&lt;!Sierra)\.dmg</string>
	</dict>
```

I want to have the x86_64 version, not the arm64.  However, GitHubReleasesInfoProvider picks arm64 because it's first alphabetically?  

I can feed a DMG with ```--pkg``` or change the Regex, but I wonder if there's another way to do it?  

For my purposes, I only need x86_64, but obviously needs differ.

**Comment by n8felton** [comment]
Fixed with #131. Thanks @grahampugh!
