### ISSUE TITLE
Edge recipe failing due to pkg rename

### ISSUE THREAD

**Issue by chelming** [autopkg/n8felton-recipes#148]
https://github.com/autopkg/n8felton-recipes/blob/91ad09397cc2eb63677bd6b8a5a5093c7205d344/Microsoft/MicrosoftEdge.munki.recipe#L76

```
$ ls /Volumes/Data/AutoPkg/Cache/local.munki.MicrosoftEdge/unpack/
Distribution                      MicrosoftEdgeBeta-92.0.902.30.pkg Microsoft_AutoUpdate_Updater.pkg  Resources
```

What do you think? `MicrosoftEdge*.pkg` or `MicrosoftEdge%CHANNEL%*.pkg`?

**Comment by blackthroat** [comment]
I'm also affected by this and utilize multiple overrides,`Beta` and `Enterprise-Stable` channels. Perhaps I'm wrong, but I say keep it simple with `MicrosoftEdge*.pkg` as the recipe will already have it's own cache directory and declaring the channel in the filename doesn't really add any value?
