### ISSUE TITLE
IntelUnite.download Download Fails

### ISSUE THREAD

**Issue by foigus** [autopkg/n8felton-recipes#155]
It appears that the download mechanics for IntelUnite.download may have been greatly simplified.  It seems URLTextSearcher against the "Current" URL below should provide a valid download.  Note the not-most-current version of the software ("One-Revision-Back", below) has a different/unique URL, so the _hope_ would be that the "Current" URL is evergreen.

Current
`https://www.intel.com/content/www/us/en/download/18457/intel-unite-client-for-mac-osx.html`

One-Revision-Back
`https://www.intel.com/content/www/us/en/download/18457/30293/intel-unite-client-for-mac-osx.html`

**Comment by n8felton** [comment]
Fixed with #156
