### ISSUE TITLE
Apple Ricoh Drivers fail to download

### ISSUE THREAD

**Issue by macmule** [autopkg/n8felton-recipes#157]
`CalledProcessError: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://updates.cdn-apple.com/2021/macos/071-41744-20210311-a48edd59-5de6-45a6-9453-28e969a63008/Ricohv3.0PrinterUpdate.dmg', '--fail', '--output', '/Users/sadmin/Library/AutoPkg/Cache/local.definition.AppleRicoRicohrinterDrivers/downloads/tmpqnzll5aq']' returned non-zero exit status 22.
`

But same issue when trying manually (https://support.apple.com/kb/DL1867?locale=en_GB), so presuming a temp issue

**Comment by n8felton** [comment]
This appears to be working again.
