### ISSUE TITLE
FirefoxDeveloperEdition.munki.recipe Curl failure: 404 Not Found

### ISSUE THREAD

**Issue by gusi1994** [autopkg/n8felton-recipes#69]
After running the recipe it returns the following error:
`Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)`

I already looked inside the recipes but I can't find the issue.

**Comment by n8felton** [comment]
Pinging @cwhits

**Comment by cwhits** [comment]
Hi @gusi1994, the FirefoxDeveloperEdition recipes in this repo have been deprecated and you can use the autopkg/recipes `Mozilla/Firefox.munki.recipe` instead. You can see autopkg/recipes#218 for more info.

The steps to use those recipes would be as follows:
```
autopkg repo-add recipes
autopkg make-override Firefox.munki.recipe -n FirefoxDeveloperEdition.munki.recipe
```
From there you will want to edit the override and change `RELEASE` to `devedition-latest` as well as updating the `NAME` and `display_name` within the pkginfo.

If you're trying to run the recipe as a one-off you can accomplish the same by doing `autopkg run Firefox.munki --key=RELEASE=devedition-latest --key=NAME=FirefoxDeveloperEdition`. However, you'll still need to update the `display_name` in munki after it imports.

**Comment by gusi1994** [comment]
Thank you for your instructions. I appreciate that.
