### ISSUE TITLE
ApplePrinterDrivers - Apple changed printer driver URLs

### ISSUE THREAD

**Issue by DCoobs** [autopkg/n8felton-recipes#73]
It appears that Apple has changed the URLs for their printer drivers.

Some sample URLs
https://support.apple.com/kb/dl1864?locale=en_US
https://support.apple.com/kb/dl1776?locale=en_US
https://support.apple.com/kb/dl1926?locale=en_US

**Comment by rmanly** [comment]
![screen shot 2017-11-13 at 09 04 58](https://user-images.githubusercontent.com/1110967/32732299-c5a9c1a8-c851-11e7-9a23-a8c713427a07.png)

**Comment by rmanly** [comment]
The funny thing is that those links are clickable in our help desk system and the downloads start.

Not sure if the downloadinfo provider doesn't follow redirects or what. Haven't poked around in the recipes.

**Comment by macmule** [comment]
Actually seems that the URL format has changed, possibly

https://support.apple.com/kb/DL1927/en_US fails
https://support.apple.com/kb/DL1927?locale=en_US works

**Comment by n8felton** [comment]
This will likely require the download recipes to switch to scraping the HTML on the support site for the path to the disk image as the redirection to the actual file has broke.

**Comment by fuzzylogiq** [comment]
It appears you can put almost any character after the /en_US/ e.g. [https://support.apple.com/downloads/DL1888/en_US/:](https://support.apple.com/downloads/DL1888/en_US/:) (which is why the links in the errors that autopkg produces are clickable!) and it will redirect you to the latest download...

**Comment by DCoobs** [comment]
Nice find!
