### ISSUE TITLE
FirefoxDeveloperEdition.munki.recipe - 404 Not Found

### ISSUE THREAD

**Issue by blackthroat** [autopkg/n8felton-recipes#75]
```
$ autopkg run -v autopkg_FirefoxDeveloperEdition.munki.recipe 
Processing autopkg_FirefoxDeveloperEdition.munki.recipe...
WARNING: autopkg_FirefoxDeveloperEdition.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
com.github.autopkg.download.firefox-rc-en_US/MozillaURLProvider
MozillaURLProvider: Found URL https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=osx&lang=en-US
URLDownloader
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.
Receipt written to /Users/ladmin/Library/AutoPkg/Cache/local.munki.autopkg_FirefoxDeveloperEdition/receipts/autopkg_FirefoxDeveloperEdition.munki-receipt-20171121-121002.plist

The following recipes failed:
    autopkg_FirefoxDeveloperEdition.munki.recipe
        Error in local.munki.autopkg_FirefoxDeveloperEdition: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)

Nothing downloaded, packaged or imported.
```

https://github.com/autopkg/recipes/blob/master/Mozilla/MozillaURLProvider.py

Instead of `firefox-aurora` should it be `firefox-devedition`?

**Comment by cwhits** [comment]
Hi @blackthroat, the FirefoxDeveloperEdition recipes in this repo have been deprecated and you can use the autopkg/recipes `Mozilla/Firefox.munki.recipe` instead. You can see autopkg/recipes#218 for more info.

The steps to use those recipes would be as follows:
```
autopkg repo-add recipes
autopkg make-override Firefox.munki.recipe -n FirefoxDeveloperEdition.munki.recipe
```
From there you will want to edit the override and change `RELEASE` to `devedition-latest` as well as updating the `NAME` and `display_name` within the pkginfo.

If you're trying to run the recipe as a one-off you can accomplish the same by doing `autopkg run Firefox.munki --key=RELEASE=devedition-latest --key=NAME=FirefoxDeveloperEdition`. However, you'd need to update the `display_name` in Munki after it imports.

**Comment by blackthroat** [comment]
Thanks for the quick response!
