### ISSUE TITLE
New support article for Epson Printer Drivers

### ISSUE THREAD

**Issue by jazzace** [autopkg/n8felton-recipes#8]
Apple updated the support article to DL1792 when they updated Epson Printer Drivers to 3.0. The old article (DL1398) still exists but is now flagged as "for OS X 10.6."

I suspect you will choose to just support the new version and change the article number in the recipe, but there are other choices (like supporting both with an input variable), so I will leave it to you to decide.

**Comment by n8felton** [comment]
Internally we've phased out 10.6 for a while and have no intentions on ever needing to support it again, so I just changed the article number in this recipe. If you (or anyone else) has a need to be able to still grab the older drivers with AutoPkg, I'm always open to pull requests.

**Comment by gregneagle** [comment]
Do we expect that Apple would ever update printer drivers for 10.6 again?

I'm of the opinion that recipes are most valuable for items that are frequently updated; still valuable for items that are infrequently updated, and much less valuable for items that are no longer updated unless some sort of transformation must be applied to get a deployable item.

Recipes that simply exist to download some old, unchanging item don't seem very interesting or useful.

**Comment by jazzace** [comment]
To be clear, I favour ditching support for 10.6 drivers, but it wasn't my recipe, so not my call.
