### ISSUE TITLE
HPPrinterDrivers..

### ISSUE THREAD

**Issue by sggr57a** [autopkg/n8felton-recipes#85]
Is it possible to create an input to gather a package URL based on model instead of product number?

**Comment by cwhits** [comment]
Do you have a model that isn't included in the `E6B70A` driver so we can test against it?

**Comment by sggr57a** [comment]
I don't know if these are included are not but how about the Laserjet m400, m401, 600?

**Comment by sggr57a** [comment]
The 4250 model doesn't appear to be included.

**Comment by MLBZ521** [comment]
I believe this ask is (will be) supported from the improvements in #175.

**Comment by n8felton** [comment]
Check to see if #175 solves your need here. If not, feel free to re-open this issue.
