### ISSUE TITLE
ApplePrinterDrivers - Apple changed printer driver URLs

### ISSUE THREAD

**Issue by dcoobs** [autopkg/n8felton-recipes#86]
It appears that Apple has changed the URLs for their printer drivers again. Doesn't look like you can add characters after the /en_US/ anymore.

[https://support.apple.com/downloads/DL1888/en_US/&](https://support.apple.com/downloads/DL1888/en_US/&) fails
[https://support.apple.com/downloads/DL1888](https://support.apple.com/downloads/DL1888) works
[https://support.apple.com/downloads/DL1888?locale=en_US](https://support.apple.com/downloads/DL1888?locale=en_US) works

**Comment by n8felton** [comment]
I think Apple was just having some issues. The processors appear to be working again without any changes. I'll keep an eye on them.

**Comment by dcoobs** [comment]
Agreed, everything seems happy now. Thanks for the quick response!
