### ISSUE TITLE
Paraview failing code signature verification

### ISSUE THREAD

**Issue by cwhits** [autopkg/n8felton-recipes#90]
Paraview isn't signing their RC's and they're offering up their RC's on their downloads page. Either a custom processor needs to be written to look for versions that are signed or we ignore it and wait for them to start signing again.

**Comment by n8felton** [comment]
Issue opened with the developer.

https://gitlab.kitware.com/paraview/paraview/issues/18629

**Comment by n8felton** [comment]
Fixed upstream. Code signature verification is passing again. (for now...)
